ITEM.name					= "M4A1"
ITEM.plural				= "M4A1s"
ITEM.size					= 5
ITEM.cost					= 4200
ITEM.model				= "models/weapons/w_rif_m4a1.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.description	= "39mm mid-range carbine with a 16'' barrel and a retractable stock."
ITEM.ammo					= "5.56x45MM"
ITEM.weaponType		= TYPE_LARGE
ITEM.base					= "weapon"
