ITEM.name					= "AWM"
ITEM.plural				= "AWMs"
ITEM.size					= 6
ITEM.cost					= 6500
ITEM.model				= "models/weapons/w_cstm_l96.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.description	= "Long-range, bolt action, Arctic Warfare Magnum; Chambered for .338 ."
ITEM.ammo					= ".338 Lapua"
ITEM.weaponType		= TYPE_LARGE
ITEM.base					= "weapon"
