ITEM.name					= "Manurhin 96"
ITEM.plural				= "Manurhin 96s"
ITEM.size					= 2
ITEM.cost					= 1750
ITEM.model				= "models/weapons/w_357.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.description	= "A .38 double-action revolver."
ITEM.ammo					= ".44 Magnum"
ITEM.weaponType		= TYPE_SMALL
ITEM.base					= "weapon"
