CustomizableWeaponry:addFireSound("CW_BER_SCOOT_FIRE", "weapons/cw_ber_scoot/shot3.wav", 1, 100, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_BER_SCOOT_FIRE_SUPPRESSED", "weapons/cw_ber_scoot/shots.wav", 1, 100, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_MAGOUT", "weapons/cw_ber_scoot/clipout.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_MAGIN", "weapons/cw_ber_scoot/clipin.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_MAGRELEASE", "weapons/cw_ber_scoot/magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_BOLTBACK", "weapons/cw_ber_scoot/boltback2.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_BOLTHANDLE", "weapons/cw_ber_scoot/bolthandle2.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_BOLTFORWARD", "weapons/cw_ber_scoot/boltforward2.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_BOLTBACKS", "weapons/cw_ber_scoot/boltbacks.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_BOLTHANDLES", "weapons/cw_ber_scoot/bolthandles.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_BOLTFORWARDS", "weapons/cw_ber_scoot/boltforwards.wav")
CustomizableWeaponry:addReloadSound("CW_BER_SCOOT_DRAW", "weapons/cw_ber_scoot/draw.wav")
