ITEM.name					= "AR2 Rounds"
ITEM.size					= 1
ITEM.cost					= 1000
ITEM.model				= "models/items/boxmrounds.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.plural				= "AR2 Rounds"
ITEM.description	= "Rounds for the AR2"
ITEM.base					= "ammo"
ITEM.ammo					= {"ar2", 30}
