ITEM.name					= "5.45x39MM Rounds"
ITEM.size					= 1
ITEM.cost					= 1500
ITEM.model				= "models/Items/BoxMRounds.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.plural				= "5.45x39MM Rounds"
ITEM.description	= "Rounds for 39mm assualt rifles."
ITEM.base					= "cw_ammo_ent_base"
ITEM.ammo					= {"5.45x39MM", 30}
