ITEM.name					= "9x19mm Rounds"
ITEM.size					= 1
ITEM.cost					= 650
ITEM.model				= "models/Items/BoxSRounds.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.plural				= "9x19mm Rounds"
ITEM.description	= "Rounds for 9mm weapons."
ITEM.base					= "cw_ammo_ent_base"
ITEM.ammo					= {"9x19MM", 30}
