ITEM.name					= ".338 Lapua Rounds"
ITEM.size					= 1
ITEM.cost					= 2500
ITEM.model				= "models/Items/BoxMRounds.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.plural				= ".338 Lapua Rounds"
ITEM.description	= "Rounds for any kind of automatic rifle."
ITEM.base					= "cw_ammo_ent_base"
ITEM.ammo					= {".338 Lapua", 5}
