ITEM.name					= "5.56x45MM Rounds"
ITEM.size					= 1
ITEM.cost					= 1500
ITEM.model				= "models/Items/BoxMRounds.mdl"
ITEM.batch				= 10
ITEM.store				= true
ITEM.plural				= "5.56x45MM Rounds"
ITEM.description	= "Rounds for 45mm assualt rifles."
ITEM.base					= "ammo"
ITEM.ammo					= {"5.56x45MM", 30}
